### ISSUE TITLE
Classes in documentation show "default" instead of their intended class names

### ISSUE THREAD

**Issue by danbopes** [samliew/chatexchange#160]
See https://samliew.github.io/chatexchange/classes/Message.default.html:

This function should return `Promise<User>` but instead shows `Promise<default>` (This happens frequently throughout the docs).

![](https://i.imgur.com/zN7BpVW.png)

Would be nice to show the actual class names instead of default. (Probably some ES6 thing with the default export).

**Comment by Oaphi** [comment]
This issue on the `typedoc` source repo seems relevant: TypeStrong/typedoc/issues/1521

**Comment by Oaphi** [comment]
Perfect fix, a PR coming right up:

![ice_screenshot_20220305-034416](https://user-images.githubusercontent.com/34833340/156860110-736c4532-bdf7-48b8-b76d-38637d1c0a91.png)
