### ISSUE TITLE
Update GitHub pages reference & republish

### ISSUE THREAD

**Issue by Oaphi** [samliew/chatexchange#19]
@samliew - I was poking around the repo and noticed that the repo "about" points to the old Pages: `danbopes.github.io/chatexchange/` whereas it should point to the `https://samliew.github.io/chatexchange/`.
I don't have enough privileges on the repo to update it - could you do that, please?

Other than that, after a couple of battles with outdated dependencies, the repo should be in a workable state - I will continue upgrading it and hopefully will bring it to the 1.0.0 stable release.

**Comment by Oaphi** [comment]
The same goes for publishing the package on NPM - I just fixed the `enum` (it was easy to convert it into an array) and would like to republish the package to at least 0.3.0 (the version is non-breaking and tested, so should be good to go).

**Comment by danbopes** [comment]
I can check access wise if you're unable to publish to npm. I think I gave Samuel access, but let me know if it should change

**Comment by Oaphi** [comment]
Hi @danbopes! Most likely they have access - I just got the repository a couple of hours ago and finished fiddling with the dependency pull requests and adding GitHub workflow to it. It just occurred to me that I cannot republish and I forgot to ask @samliew about it when we discussed maintenance.

**Comment by samliew** [comment]
I've never published to NPM before. What do I need to do?

**Comment by Oaphi** [comment]
@samliew - as far as I recall, not much, if you are the owner or of the repository, it should be as simple as running an `npm publish` on local and authorizing as the user (either manually or by configuring credentials but that's a more involved process). I've never inherited a published npm package before, though, so I can't tell if there are additional steps required.

I actually want to set up a GitHub workflow to automatically publish upon release to avoid doing this manually.

**Comment by samliew** [comment]
@danbopes I logged in to NPM via terminal `npm login`, then tried to `npm publish`

> npm ERR! code E403
> npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/chatexchange - You do not have permission to publish "chatexchange". Are you logged in as the correct user? 

My NPM username is samliew , email samliew@gmail.com

**Comment by Oaphi** [comment]
@samliew I think [this link](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) should help. Just in case, but I am sure you know about it - cc @danbopes

**Comment by danbopes** [comment]
@samliew You should have received an invite.

**Comment by Oaphi** [comment]
thank you, @samliew and @danbopes! I noticed we have a Travis CI build failure because of the Coveralls issue "Couldn't find a repository matching this job.". I don't think it's a big deal but we should probably address this sometime. Also, I would like to propose switching to GitHub workflows to keep all things here and avoid the need to manage account access, etc. @samliew  - what do you think? I can update both branches to include a standard build flow.

**Comment by samliew** [comment]
I've fixed the badges, which also resolved the Travis CI build failure

> I can update both branches to include a standard build flow.

Yes go ahead please, never did a build flow via GitHub before and would be nice to learn something new.

**Comment by Oaphi** [comment]
@samliew thanks! Huh, that was it, I should've looked better - just the Travis migrating to the com domain.
Re: build via GitHub - actually, the flow was added a couple of commits ago, I just added another step that runs the build now. It's surprisingly easy - a simple YAML with the workflow configuration and that's it. Runs both on push and pull requests to be extra sure.

@samliew @danbopes is the master branch in JS really needed, btw? I think it is safe to assume that any further development will happen on the TypeScript branch only. Is there any downside to scrapping the branch and making the TS one the master branch?

**Comment by samliew** [comment]
Hey @Oaphi, I'll make you lead on the chatexchange js project, feel free to make any changes as necessary. If you need my input just create a new issue and I'll take a look as well.

Re: master branch, it was because the typescript branch was developed separately and wasn't extensively tested. If you are comfortable with it being master feel free to rebase.

**Comment by Oaphi** [comment]
Heya @samliew - thanks, will try not to break the build too much :) I just thought of an easier way of communicating over the project should the need arise: [Discussions](https://github.com/samliew/chatexchange/discussions), I think it will be easier than opening an issue every time I need to tell something important.

Re: master - thank you for clarifying, I will go ahead then and override the master branch with TypeScript - pretty sure everything works fine right now, and with the workflows setup, we will know when things go south in the future. Keeping two unrelated branches right now is too of a maintenance toll. I will make sure TS is thoroughly tested as well once I get to understand the source better.
